### ISSUE TITLE
CSRF error on iPhone login

### ISSUE THREAD

**Issue by madprime** [OpenHumans/open-humans#544]
Unclear what is causing this or how to reproduce. Login via iPhone started producing CSRF error. It didn't originally. One thing that changed was approving "store password for future logins" (unclear if/how this would affect the form).

**Comment by gedankenstuecke** [comment]
I could reproduce this bug once now. 

I think it happens if you click `login` twice in succession which can happen especially when the website is slow and you think you didn't hit it properly. 

If you push the button twice the same problem will occur outside an iPhone as well. So it's a general thing and probably kind of expected behavior as the csrf-token is already used by the second time you press the button.
