### ISSUE TITLE
Use same serializer for direct-sharing and public data APIs

### ISSUE THREAD

**Issue by beaugunderson** [OpenHumans/open-humans#550]
"Public Data Sharing" looks like data I might get if I were running a project that requested access to all types of data from members.

BUT public data sharing doesn't make sense to share "whether authorized to send messages" and other project enrollment specific information.

**Comment by madprime** [comment]
Closing this as too much work / too dangerous due to the framework we use. The REST framework is tricky about re-using model serializers -- it's hard to subclass and _add_ fields.

That's bad. It means we would need to re-use a more extensive private serialization and trust ourselves to remembering to filter out sensitive stuff in a child class for public serialization. Too dangerous.
