### ISSUE TITLE
Navbar menu won't collapse on small/mobile views

### ISSUE THREAD

**Issue by madprime** [OpenHumans/open-humans#686]
The navbar menu opens on a click in small/mobile view – but clicking again does _not_ close it as it should.

This bug seems to be caused by a double inclusion of jQuery – per [this response on Stack Overflow](https://stackoverflow.com/a/26403469)? jQuery is first added in `main.js` ([see here](https://github.com/OpenHumans/open-humans/blob/28c9a6fb9ad94f666a74ec658824c6f8b25aaa35/static/js/main.js#L6)) and often (but not always) another time in a page-specific JS, e.g. `home.js` ([see here](https://github.com/OpenHumans/open-humans/blob/28c9a6fb9ad94f666a74ec658824c6f8b25aaa35/static/js/home.js#L3)).

It's unclear how long this issue has been on the site… if this diagnosis is correct, this double-includes might be causing other issues.

**Comment by gedankenstuecke** [comment]
Ok, from what i can see this only happens with the member list, which made problems earlier (see #662). See it in action at https://staging.openhumans.org/members/ 

There seems to be some weird conflict with jquery again, @beaugunderson do you have an idea what goes wrong here? :)

**Comment by madprime** [comment]
I'm a bit stuck trying to get it to work locally, actually (on the old version of the code). I've gone back to that commit... run npm update... I wish I were more proficient, sorry!

(And I'm also confessing that I had merged without attempting to test locally before – I'm afraid there's a lot on my plate these days.)

**Comment by beaugunderson** [comment]
i think the issue may not be that jQuery is loaded twice, since each copy
should be in its own bundle, but that the second load overwrites
window.jQuery, which probably messes up the events system...

one fix may be to take jQuery out of the bundle entirely (and load it from
e.g. cdnjs.com before main.js and the page bundle js), then take all the
`var $ = window.jQuery` lines out entirely and rely on the global jQuery
