### ISSUE TITLE
Improve message a member feature

### ISSUE THREAD

**Issue by danamlewis** [OpenHumans/open-humans#721]
1) Logged in to message a member, then in another browser (I thought different type of browser, but was same browser type) logged in to another account to check where something was. Then sending the message borked to this. May be beyond OH control, but would be nice to have a better error message if at all possible, or the ability to go back to the previous screen with the text saved. (Pipe dreams perhaps?)
![screen shot 2018-02-06 at 4 26 15 pm](https://user-images.githubusercontent.com/7468165/35891925-87d6f470-0b5b-11e8-95b4-e0a3ee4f6bc1.png)

2) Made me realize that it's hard to ensure you're in the right account and messaging the right project participants. Would be nice to have some indication of the project you're messaging about on the message page:
<img width="622" alt="screen shot 2018-02-06 at 4 28 49 pm" src="https://user-images.githubusercontent.com/7468165/35891931-8e79e0c6-0b5b-11e8-9809-5f6170f9803c.png">

**Comment by beaugunderson** [comment]
persisting the form content is easy enough since the site already has garlicjs; adding `rel="persist"` to the `<form>` should be sufficient

**Comment by beaugunderson** [comment]
would be nice to catch the CSRF exception in the form code but since it's middleware not sure how/if possible... the form persistence is the biggest win though

**Comment by madprime** [comment]
Oooh, thank you for the pointer to the garlicjs thing! (I'm so JS illiterate, I should learn more!) :D

It looks like setting CSRF_FAILURE_VIEW can be set to make a friendlier error page. :)

**Comment by madprime** [comment]
I think this error is likely to have arisen due to the account switch (one browser can't be logged in to two different accounts) ... and in local testing, after I trigger a CSRF error in this manner, I can't go back to the page (it's 404 due to permissions) ... and "logging back in as User 1" does not recover the content.

It's still good to add all suggestions here, I'll go ahead and do that now...

But this also points to the need for #667!
