### ISSUE TITLE
Create Nokia Health oauth2 project

### ISSUE THREAD

**Issue by gedankenstuecke** [OpenHumans/open-humans#747]
https://github.com/Treblesteph/oh-nokiahealth-integration

**Project app**
- [x] Open Humans authorization
- [x] Nokia Health token authorization (Nokia health is "OAuth1")
- [x] Set up on Heroku / Open Humans project ready for all members
- [x] Token import script ready
- [x] fix dashboard and triggering data import

Data fetching
- [x] find start dates correctly, needs testing
- [x] test that data import/upload works  
- [x] add data import to user sign in
- [x] write task for periodic data updates 

**Ops/Deployment**
- [x] Deploy external project
- [x] Shutdown legacy integration (Mad)
- [x] Get existing OAuth1 tokens for members (Mad)
- [x] Import old tokens into stand-alone project
- [x] set up heroku scheduler

**Comment by mcescalante** [comment]
Things completed:

- Refactor of Nokia OAuth1 handshake
- Remove/not use old `BaseSource` class
- Fetching of Nokia Data
  - Activity
  - Measure
  - Intraday
  - Sleep
  - Sleep Summary
  - Workouts

Up next:

- Upload data returned as files to OH
- Deploy the project to test it live

**Comment by mcescalante** [comment]
Completed in the last few days by @Treblesteph:

1. All data is uploaded to OH after being fetched from Nokia Health
2. Application is functioning deployed to heroku at `http://oh-nokiahealth-integration.herokuapp.com/`

Up next:

- Vizualizations for data post 
- Further testing
- Additional code refactoring and cleanup
- Maybe switch the OH upload over to use the `open-humans-api` S3 method rather than the previous `xfer_to_open_humans` method.

**Comment by mcescalante** [comment]
Done:

- Add rate limiting via requests-respectful
- Move celery from RabbitMQ (amqp) to Redis

Up next:
- Additional tests, fix broken existing ones
- Scheduled data update tasks
- Finalize deployment
- Start with existing token import/regeneration for standalone project

**Comment by gedankenstuecke** [comment]
Automatic updates are fixed with [OpenHumans/oh-nokiahealth-integration#26](https://github.com/OpenHumans/oh-nokiahealth-integration/pull/26) and set up in `heroku scheduler`. Done with it for now.
