### ISSUE TITLE
Add "Get Involved" page to main OH site

### ISSUE THREAD

**Issue by gedankenstuecke** [OpenHumans/open-humans#748]
List ways in how people can interact with Open Humans. Starting from blogging/tweeting/slacking (off) over sharing data to running their own projects

**Comment by madprime** [comment]
I'd like to better understand how this proposed page fits into the whole site? What's going to link to it? How does someone find it? How important should it be? Is it redundant with anything that's already present? (Should that be cut?)

I'm concerned because I think there's been a process of adding "page for X" without thinking about the overall layout and UX of finding stuff across all our pages, and we end up with a lot of content people aren't aware of -- including our own team.

**Comment by gedankenstuecke** [comment]
As we've discussed over the last week: Right now it's really hard to see (or even explain) how users can interact with OH. The "get involved" page should be a hub for all calls to action, sorted by level of involvement. 

Ultimately it would be great if this could be front & center and replace a good parts of the different sub-sites which are right now hard to find (e.g. I can't find our public data "lists" without poking on the site), but this will probably be a larger thing for the UI/UX overhaul that we discussed as a potential next project after the site has been cleaned from historical artifacts and runs on modern software. 

Until then I see that this could be a good extension for the `about us` page.

**Comment by madprime** [comment]
Closing this as obsolete.

We _do_ need better communication as part of UX/UI improvements. But guides should be the least-favorite solution. We'll leave which/what guides are needed until later, preferably in response to more deliberate usability testing & observations. :)
