### ISSUE TITLE
run static analyser to identify py2->py3 issues

### ISSUE THREAD

**Issue by gedankenstuecke** [OpenHumans/open-humans#781]
Run an analyser to see where our existing code base will run into issues with Python3.

**Comment by mcescalante** [comment]
Here is a diff of the changes that are suggested/required to upgrade from python 2 to python 3: https://gist.github.com/mcescalante/220ecd4e3afb91aed7d6add5cf9686b6

The same changes are also pushed as a single commit to a branch in my fork [located here](https://github.com/mcescalante/open-humans/tree/py3) and this is the diff link (going to be the same as the link above, but likely more readable): https://github.com/mcescalante/open-humans/commit/6595be6c6a5d9c09d6438598d4740645e702b073

**Comment by mcescalante** [comment]
Okay, I just updated the links above with a different branch, `py3-fix`, in which I fixed the extra parenthesis being added to `print()` statements (that are already python 3 safe). I also added a note about how this tool may not catch third party library upgrade related changes, since some libraries (if we must update any older versions to get Python 3 compatibility) may have made some deprecations or changes depending on what version we're using and how outdated it may be.

**Comment by jhdulaney** [comment]
Closing as the python3 migration is complete.
